<?php
/* @var Espl\BookShelf\Block\Form $block */
$books = $block->getAllBooks();
?>
    <h2>Add Book Detail</h2>
    <form method="post" action="<?php echo $block->getUrl('bookshelf/book/add') ?>">
        <fieldset>
            <div>
                <label for="model"><?php echo __("BookName") ?></label>
                <input type="text" name="bookname" id="bookname" class="input-text" data-validate="{required:true, 'validate-alphanum-with-spaces':true} />
            </div>
            <div>
                <label for="model"><?php echo __("Author") ?>
                    <input type="text" name="author" id="author"
                     class="input-text" data-validate="{required:true, 'validate-alphanum-with-spaces':true}/>
            </div>
            <div>
                <label for="model"><?php echo __("Description") ?></label>
                    <textarea class="FormElement" name="term" id="term" cols="40" rows="4"></textarea>
            </div>
            <input type="submit" class="action submit primary" value="<?php echo __("Add Book") ?>" />
        </fieldset>
    </form>
    