<h2>Users Reviews</h2>

<div class="row">
    <div class="col-md-8">
        <form method="post"  class="form"
              action="<?= $block->escapeUrl($block->getAddDataPostUrl()) ?>" 
              data-hasrequired="* Required Fields"
              data-mage-init='{"validation":{}}'>
                        
            <fieldset class="fieldset">
                <legend class="legend"><span>Fill Review about our Website</span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span>Title</span></label>
                            <div class="control">
                                <input name="title" id="title" title="Title" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        
                        <div class="field name required">
                            <label class="label" for="title"><span>Description</span></label>
                            <div class="control">
                                <input name="description" id="description" title="Description" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>

                        <div class="field frame_name required">
                            <label class="label" for="frame_name"><span>Rating</span></label>
                            <div class="control">
                                <select name="rating" id="rating" title="Rating" class="input-text" data-validate="{required:true}">
                                    <option value=""><?php echo __('Please Select Rating') ?></option>
                                    <option value="1"><?php echo __('1') ?></option>    
                                    <option value="2"><?php echo __('2') ?></option>    
                                    <option value="3"><?php echo __('3') ?></option> 
                                    <option value="4"><?php echo __('4') ?></option>
                                    <option value="5"><?php echo __('5') ?></option>
                                </select>
                            </div>
                        </div>

                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span>Save</span></button>
                </div>
            </div>
        </form>
    </div>
</div>
